name: CDE tests

on: [push]

jobs:
  python_tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [ '3.9', '3.11' ]
    name: Test on Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Set up Selenium
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
        mkdir geckodriver
        tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
        export PATH=$PATH:$PWD/geckodriver
    - name: Install dependencies
      run: |
        # Install documentation dependencies (not in pyproject.toml)
        uv add --group docs nbsphinx==0.3.5 nbsphinx-link m2r2 ipython ipykernel sphinx-rtd-theme future==0.17.1
        # Install project with development dependencies
        uv sync --group dev --group docs
        uv run cde data download
    - name: Running tests
      run: |
        uv run pytest -W ignore::DeprecationWarning
